/**
 * @file packages/mock-deliverect/src/orders.ts
 * Generates realistic retail grocery orders for testing Deliverect Generic Picking API.
 */

import { PickingOrder, ItemUnavailableAction } from '../../contracts/src/index.js';
import { createQP02GroupedOrder } from './qp02-fixture.js';

export { createQP02GroupedOrder };

export function createSampleGroceryOrders(locationId: string = 'loc_london_flagship'): PickingOrder[] {
  const now = Date.now();

  const groupedOrder = createQP02GroupedOrder(locationId);

  const order1: PickingOrder = {
    _id: 'deliv_ord_' + Math.random().toString(36).substring(2, 9),
    location: locationId,
    channelOrderId: 'UBER-' + Math.floor(100000 + Math.random() * 900000),
    channelOrderDisplayId: '#UB-4821',
    pickupTime: new Date(now + 25 * 60 * 1000).toISOString(), // due in 25 mins
    deliveryTime: new Date(now + 40 * 60 * 1000).toISOString(),
    orderType: 'DELIVERY',
    customer: {
      name: 'Oliver Twist',
      phone: '+44 7700 900123',
      email: 'oliver@example.co.uk',
    },
    note: 'Please pick fresh, green bananas if available. Fragile items on top!',
    status: 'SCHEDULED',
    pickerStatus: 'NOT_STARTED',
    receivedAt: new Date(now - 2 * 60 * 1000).toISOString(),
    dueAt: new Date(now + 25 * 60 * 1000).toISOString(),
    items: [
      {
        _id: 'item_bananas_001',
        plu: '4011',
        name: 'Fairtrade Organic Bananas (Bunch)',
        quantity: 1,
        price: 185, // £1.85
        channelItemId: 'ch_4011',
        gtin: ['0000004011001', '040110000000'],
        department: 'Fresh Produce',
        aisle: 'Aisle 1',
        shelf: 'Bay 2 - Lower Shelf',
        sequence: 1,
        temperature: 'AMBIENT',
        isWeight: true,
        weightUnit: 'kg',
        expectedWeight: 1.25,
        minWeight: 0.8,
        maxWeight: 1.8,
        itemUnavailableActions: ['ITEM_SUBSTITUTION', 'ITEM_REMOVE'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
      },
      {
        _id: 'item_sourdough_002',
        plu: '502345',
        name: 'Artisan San Francisco Sourdough Bread 500g',
        quantity: 2,
        price: 320,
        channelItemId: 'ch_502345',
        gtin: ['5060123456789'],
        department: 'Bakery',
        aisle: 'Aisle 2',
        shelf: 'Bay 1 - Eye Level',
        sequence: 2,
        temperature: 'AMBIENT',
        isWeight: false,
        itemUnavailableActions: ['ITEM_AMENDMENT', 'ITEM_SUBSTITUTION', 'ITEM_REMOVE'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=800&auto=format&fit=crop&q=80',
      },
      {
        _id: 'item_oatmilk_003',
        plu: '735005',
        name: 'Oatly Barista Edition Oat Milk 1L',
        quantity: 3,
        price: 210,
        channelItemId: 'ch_735005',
        gtin: ['7350052850015'],
        department: 'Chilled Dairy & Plant',
        aisle: 'Aisle 5',
        shelf: 'Bay 3 - Mid Shelf',
        sequence: 3,
        temperature: 'CHILLED',
        isWeight: false,
        itemUnavailableActions: ['ITEM_AMENDMENT', 'ITEM_REMOVE'] as ItemUnavailableAction[], // note: no substitution allowed!
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=80',
      },
      {
        _id: 'item_cheddar_004',
        plu: '501029',
        name: 'Cathedral City Extra Mature Cheddar 350g',
        quantity: 1,
        price: 450,
        channelItemId: 'ch_501029',
        gtin: ['5010293847120'],
        department: 'Chilled Dairy',
        aisle: 'Aisle 5',
        shelf: 'Bay 4 - Top Shelf',
        sequence: 4,
        temperature: 'CHILLED',
        isWeight: false,
        itemUnavailableActions: ['ITEM_SUBSTITUTION', 'ITEM_SUBSTITUTION_CATALOG', 'ITEM_REMOVE'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=800&auto=format&fit=crop&q=80',
      },
      {
        _id: 'item_icecream_005',
        plu: '871132',
        name: "Ben & Jerry's Cookie Dough Ice Cream 465ml",
        quantity: 1,
        price: 550,
        channelItemId: 'ch_871132',
        gtin: ['8711327371089'],
        department: 'Frozen Desserts',
        aisle: 'Aisle 8',
        shelf: 'Freezer 2',
        sequence: 5,
        temperature: 'FROZEN',
        isWeight: false,
        itemUnavailableActions: ['ITEM_SUBSTITUTION', 'ITEM_REMOVE'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&auto=format&fit=crop&q=80',
      },
    ],
  };

  const order2: PickingOrder = {
    _id: 'deliv_ord_' + Math.random().toString(36).substring(2, 9),
    location: locationId,
    channelOrderId: 'DELIVEROO-' + Math.floor(100000 + Math.random() * 900000),
    channelOrderDisplayId: '#DLV-9012',
    pickupTime: new Date(now + 12 * 60 * 1000).toISOString(), // urgent, due in 12 mins
    deliveryTime: new Date(now + 25 * 60 * 1000).toISOString(),
    orderType: 'DELIVERY',
    customer: {
      name: 'Maya Lin',
      phone: '+44 7890 123456',
    },
    note: 'ID check required for beverage. Ring flat 3B buzzer.',
    status: 'SCHEDULED',
    pickerStatus: 'NOT_STARTED',
    receivedAt: new Date(now - 10 * 60 * 1000).toISOString(),
    dueAt: new Date(now + 12 * 60 * 1000).toISOString(),
    items: [
      {
        _id: 'item_beer_101',
        plu: '501234',
        name: 'Camden Hells Lager 4 x 330ml Can Pack',
        quantity: 2,
        price: 720,
        channelItemId: 'ch_beer_101',
        gtin: ['5012349876543'],
        department: 'Beer, Wine & Spirits',
        aisle: 'Aisle 3',
        shelf: 'Bay 1 - Floor Stack',
        sequence: 1,
        temperature: 'AMBIENT',
        ageRestricted: true,
        minimumAge: 18,
        itemUnavailableActions: ['ITEM_SUBSTITUTION', 'CANCEL_ORDER'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1608270546103-979929285746?w=300&auto=format&fit=crop&q=60',
      },
      {
        _id: 'item_crisps_102',
        plu: '500016',
        name: 'Walkers Sensations Thai Sweet Chilli Crisps 150g',
        quantity: 2,
        price: 240,
        channelItemId: 'ch_crisps_102',
        gtin: ['5000168012345'],
        department: 'Snacks',
        aisle: 'Aisle 3',
        shelf: 'Bay 3 - Eye Level',
        sequence: 2,
        temperature: 'AMBIENT',
        itemUnavailableActions: ['ITEM_AMENDMENT', 'ITEM_REMOVE', 'ITEM_SUBSTITUTION'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300&auto=format&fit=crop&q=60',
      },
      {
        _id: 'item_loose_avocado_103',
        plu: '4225',
        name: 'Ripe & Ready Hass Avocados (Torn Barcode)',
        quantity: 2,
        price: 195,
        channelItemId: 'ch_avocado_103',
        gtin: [], // Missing barcode! Test Altie AI Photo Recognition / PLU lookup
        department: 'Fresh Produce',
        aisle: 'Aisle 1',
        shelf: 'Bay 1 - Table Display',
        sequence: 3,
        temperature: 'AMBIENT',
        itemUnavailableActions: undefined, // test absent itemUnavailableActions (tolerant parser + warning)
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=300&auto=format&fit=crop&q=60',
      },
    ],
  };

  const order3: PickingOrder = {
    _id: 'deliv_ord_' + Math.random().toString(36).substring(2, 9),
    location: locationId,
    channelOrderId: 'JUSTEAT-' + Math.floor(100000 + Math.random() * 900000),
    channelOrderDisplayId: '#JE-1055',
    pickupTime: new Date(now + 4 * 60 * 1000).toISOString(), // Critical SLA! < 5 mins
    deliveryTime: new Date(now + 15 * 60 * 1000).toISOString(),
    orderType: 'PICKUP',
    customer: {
      name: 'Sophia Patel',
      phone: '+44 7555 432109',
    },
    status: 'SCHEDULED',
    pickerStatus: 'NOT_STARTED',
    receivedAt: new Date(now - 20 * 60 * 1000).toISOString(),
    dueAt: new Date(now + 4 * 60 * 1000).toISOString(),
    items: [
      {
        _id: 'item_strawberries_201',
        plu: '503344',
        name: 'British Strawberries Punnet 400g',
        quantity: 1,
        price: 350,
        channelItemId: 'ch_strawberries_201',
        gtin: ['5033441122334'],
        department: 'Fresh Produce',
        aisle: 'Aisle 1',
        shelf: 'Bay 4',
        sequence: 1,
        temperature: 'CHILLED',
        itemUnavailableActions: ['ITEM_REMOVE', 'ITEM_SUBSTITUTION'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=300&auto=format&fit=crop&q=60',
      },
      {
        _id: 'item_pizza_202',
        plu: '761303',
        name: 'Ristorante Pepperoni Sourdough Pizza 320g',
        quantity: 2,
        price: 420,
        channelItemId: 'ch_pizza_202',
        gtin: ['7613035467891'],
        department: 'Frozen Food',
        aisle: 'Aisle 8',
        shelf: 'Freezer 1',
        sequence: 2,
        temperature: 'FROZEN',
        itemUnavailableActions: ['ITEM_AMENDMENT', 'ITEM_REMOVE'] as ItemUnavailableAction[],
        status: 'PENDING',
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300&auto=format&fit=crop&q=60',
      },
    ],
  };

  return [groupedOrder, order1, order2, order3];
}
